// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUyqeftmNMw6wLka0w9NIaLAVpj_rWydA',
    appId: '1:179829185348:web:45ee426a62a296418a1511',
    messagingSenderId: '179829185348',
    projectId: 'pog-up-conciergerie-fcm',
    authDomain: 'pog-up-conciergerie-fcm.firebaseapp.com',
    storageBucket: 'pog-up-conciergerie-fcm.firebasestorage.app',
    measurementId: 'G-CRB3YL10JM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKsrZhWmyqx7orV5bRUupkM0NvjXdBSP8',
    appId: '1:179829185348:android:d7b0515e865078628a1511',
    messagingSenderId: '179829185348',
    projectId: 'pog-up-conciergerie-fcm',
    storageBucket: 'pog-up-conciergerie-fcm.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAScKdWF3IkHYA2Kg1VBn7YowKzJoFQwpA',
    appId: '1:179829185348:ios:cd09ba044b99d9f88a1511',
    messagingSenderId: '179829185348',
    projectId: 'pog-up-conciergerie-fcm',
    storageBucket: 'pog-up-conciergerie-fcm.firebasestorage.app',
    iosBundleId: 'com.gytx.pogupConciergerie',
  );
}
